// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCvCeoFt2bZeoriiaFSmAMHn1-q3Pfajw',
    appId: '1:137349660494:web:8025d374f4b24b6c83a81f',
    messagingSenderId: '137349660494',
    projectId: 'cafe-ce36a',
    authDomain: 'cafe-ce36a.firebaseapp.com',
    storageBucket: 'cafe-ce36a.appspot.com',
    measurementId: 'G-TWY9CG581J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdjIa4MTYokiKsTgnoEhJL2aVSVubkPHk',
    appId: '1:137349660494:android:cdb801e65a64b07883a81f',
    messagingSenderId: '137349660494',
    projectId: 'cafe-ce36a',
    storageBucket: 'cafe-ce36a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJeGAaEp9wp1IIlg1ZUlTB2cw0tqh7RN4',
    appId: '1:137349660494:ios:c4e37453c20a216483a81f',
    messagingSenderId: '137349660494',
    projectId: 'cafe-ce36a',
    storageBucket: 'cafe-ce36a.appspot.com',
    iosBundleId: 'com.example.cafeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJeGAaEp9wp1IIlg1ZUlTB2cw0tqh7RN4',
    appId: '1:137349660494:ios:e7782c92af3ac06283a81f',
    messagingSenderId: '137349660494',
    projectId: 'cafe-ce36a',
    storageBucket: 'cafe-ce36a.appspot.com',
    iosBundleId: 'com.example.cafeShop.RunnerTests',
  );
}
